package com.ulic.core.sms.bean;

import java.io.Serializable;
import java.util.Date;

public class Sms implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.sms_id
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private Long smsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.sms_channel_id
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private Long smsChannelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.sms_type
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private String smsType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.sms_data
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private String smsData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.sms_receiver
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private String smsReceiver;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.remark
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.sms_sent_status
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private Integer smsSentStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.sms_status_message
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private String smsStatusMessage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.sms_sent_time
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private Date smsSentTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.sms_retry_times
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private Integer smsRetryTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.sms_retry_flag
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private String smsRetryFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.client_ip
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private String clientIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.handler_server
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private String handlerServer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.created_time
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sms.updated_time
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private Date updatedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sms
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.sms_id
	 * @return  the value of sms.sms_id
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public Long getSmsId() {
		return smsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.sms_id
	 * @param smsId  the value for sms.sms_id
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setSmsId(Long smsId) {
		this.smsId = smsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.sms_channel_id
	 * @return  the value of sms.sms_channel_id
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public Long getSmsChannelId() {
		return smsChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.sms_channel_id
	 * @param smsChannelId  the value for sms.sms_channel_id
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setSmsChannelId(Long smsChannelId) {
		this.smsChannelId = smsChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.sms_type
	 * @return  the value of sms.sms_type
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public String getSmsType() {
		return smsType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.sms_type
	 * @param smsType  the value for sms.sms_type
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setSmsType(String smsType) {
		this.smsType = smsType == null ? null : smsType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.sms_data
	 * @return  the value of sms.sms_data
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public String getSmsData() {
		return smsData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.sms_data
	 * @param smsData  the value for sms.sms_data
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setSmsData(String smsData) {
		this.smsData = smsData == null ? null : smsData.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.sms_receiver
	 * @return  the value of sms.sms_receiver
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public String getSmsReceiver() {
		return smsReceiver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.sms_receiver
	 * @param smsReceiver  the value for sms.sms_receiver
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setSmsReceiver(String smsReceiver) {
		this.smsReceiver = smsReceiver == null ? null : smsReceiver.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.remark
	 * @return  the value of sms.remark
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.remark
	 * @param remark  the value for sms.remark
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.sms_sent_status
	 * @return  the value of sms.sms_sent_status
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public Integer getSmsSentStatus() {
		return smsSentStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.sms_sent_status
	 * @param smsSentStatus  the value for sms.sms_sent_status
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setSmsSentStatus(Integer smsSentStatus) {
		this.smsSentStatus = smsSentStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.sms_status_message
	 * @return  the value of sms.sms_status_message
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public String getSmsStatusMessage() {
		return smsStatusMessage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.sms_status_message
	 * @param smsStatusMessage  the value for sms.sms_status_message
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setSmsStatusMessage(String smsStatusMessage) {
		this.smsStatusMessage = smsStatusMessage == null ? null
				: smsStatusMessage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.sms_sent_time
	 * @return  the value of sms.sms_sent_time
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public Date getSmsSentTime() {
		return smsSentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.sms_sent_time
	 * @param smsSentTime  the value for sms.sms_sent_time
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setSmsSentTime(Date smsSentTime) {
		this.smsSentTime = smsSentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.sms_retry_times
	 * @return  the value of sms.sms_retry_times
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public Integer getSmsRetryTimes() {
		return smsRetryTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.sms_retry_times
	 * @param smsRetryTimes  the value for sms.sms_retry_times
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setSmsRetryTimes(Integer smsRetryTimes) {
		this.smsRetryTimes = smsRetryTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.sms_retry_flag
	 * @return  the value of sms.sms_retry_flag
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public String getSmsRetryFlag() {
		return smsRetryFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.sms_retry_flag
	 * @param smsRetryFlag  the value for sms.sms_retry_flag
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setSmsRetryFlag(String smsRetryFlag) {
		this.smsRetryFlag = smsRetryFlag == null ? null : smsRetryFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.client_ip
	 * @return  the value of sms.client_ip
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public String getClientIp() {
		return clientIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.client_ip
	 * @param clientIp  the value for sms.client_ip
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setClientIp(String clientIp) {
		this.clientIp = clientIp == null ? null : clientIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.handler_server
	 * @return  the value of sms.handler_server
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public String getHandlerServer() {
		return handlerServer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.handler_server
	 * @param handlerServer  the value for sms.handler_server
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setHandlerServer(String handlerServer) {
		this.handlerServer = handlerServer == null ? null : handlerServer
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.created_time
	 * @return  the value of sms.created_time
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.created_time
	 * @param createdTime  the value for sms.created_time
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sms.updated_time
	 * @return  the value of sms.updated_time
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public Date getUpdatedTime() {
		return updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sms.updated_time
	 * @param updatedTime  the value for sms.updated_time
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sms
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Sms other = (Sms) that;
		return (this.getSmsId() == null ? other.getSmsId() == null : this
				.getSmsId().equals(other.getSmsId()))
				&& (this.getSmsChannelId() == null ? other.getSmsChannelId() == null
						: this.getSmsChannelId()
								.equals(other.getSmsChannelId()))
				&& (this.getSmsType() == null ? other.getSmsType() == null
						: this.getSmsType().equals(other.getSmsType()))
				&& (this.getSmsData() == null ? other.getSmsData() == null
						: this.getSmsData().equals(other.getSmsData()))
				&& (this.getSmsReceiver() == null ? other.getSmsReceiver() == null
						: this.getSmsReceiver().equals(other.getSmsReceiver()))
				&& (this.getRemark() == null ? other.getRemark() == null : this
						.getRemark().equals(other.getRemark()))
				&& (this.getSmsSentStatus() == null ? other.getSmsSentStatus() == null
						: this.getSmsSentStatus().equals(
								other.getSmsSentStatus()))
				&& (this.getSmsStatusMessage() == null ? other
						.getSmsStatusMessage() == null : this
						.getSmsStatusMessage().equals(
								other.getSmsStatusMessage()))
				&& (this.getSmsSentTime() == null ? other.getSmsSentTime() == null
						: this.getSmsSentTime().equals(other.getSmsSentTime()))
				&& (this.getSmsRetryTimes() == null ? other.getSmsRetryTimes() == null
						: this.getSmsRetryTimes().equals(
								other.getSmsRetryTimes()))
				&& (this.getSmsRetryFlag() == null ? other.getSmsRetryFlag() == null
						: this.getSmsRetryFlag()
								.equals(other.getSmsRetryFlag()))
				&& (this.getClientIp() == null ? other.getClientIp() == null
						: this.getClientIp().equals(other.getClientIp()))
				&& (this.getHandlerServer() == null ? other.getHandlerServer() == null
						: this.getHandlerServer().equals(
								other.getHandlerServer()))
				&& (this.getCreatedTime() == null ? other.getCreatedTime() == null
						: this.getCreatedTime().equals(other.getCreatedTime()))
				&& (this.getUpdatedTime() == null ? other.getUpdatedTime() == null
						: this.getUpdatedTime().equals(other.getUpdatedTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sms
	 * @mbggenerated  Wed Aug 10 10:43:30 GMT+08:00 2016
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getSmsId() == null) ? 0 : getSmsId().hashCode());
		result = prime
				* result
				+ ((getSmsChannelId() == null) ? 0 : getSmsChannelId()
						.hashCode());
		result = prime * result
				+ ((getSmsType() == null) ? 0 : getSmsType().hashCode());
		result = prime * result
				+ ((getSmsData() == null) ? 0 : getSmsData().hashCode());
		result = prime
				* result
				+ ((getSmsReceiver() == null) ? 0 : getSmsReceiver().hashCode());
		result = prime * result
				+ ((getRemark() == null) ? 0 : getRemark().hashCode());
		result = prime
				* result
				+ ((getSmsSentStatus() == null) ? 0 : getSmsSentStatus()
						.hashCode());
		result = prime
				* result
				+ ((getSmsStatusMessage() == null) ? 0 : getSmsStatusMessage()
						.hashCode());
		result = prime
				* result
				+ ((getSmsSentTime() == null) ? 0 : getSmsSentTime().hashCode());
		result = prime
				* result
				+ ((getSmsRetryTimes() == null) ? 0 : getSmsRetryTimes()
						.hashCode());
		result = prime
				* result
				+ ((getSmsRetryFlag() == null) ? 0 : getSmsRetryFlag()
						.hashCode());
		result = prime * result
				+ ((getClientIp() == null) ? 0 : getClientIp().hashCode());
		result = prime
				* result
				+ ((getHandlerServer() == null) ? 0 : getHandlerServer()
						.hashCode());
		result = prime
				* result
				+ ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
		result = prime
				* result
				+ ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
		return result;
	}
}