package com.ulic.core.sms.bean;

import java.io.Serializable;
import java.util.Date;

public class SmsChannel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.sms_channel_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private Long smsChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.sms_channel_userid
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String smsChannelUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.sms_channel_pwd
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String smsChannelPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.sms_channel_url
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String smsChannelUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.remark
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.createtor
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String createtor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.created_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.editor
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.updated_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_channel
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.sms_channel_id
     *
     * @return the value of sms_channel.sms_channel_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public Long getSmsChannelId() {
        return smsChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.sms_channel_id
     *
     * @param smsChannelId the value for sms_channel.sms_channel_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setSmsChannelId(Long smsChannelId) {
        this.smsChannelId = smsChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.sms_channel_userid
     *
     * @return the value of sms_channel.sms_channel_userid
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getSmsChannelUserid() {
        return smsChannelUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.sms_channel_userid
     *
     * @param smsChannelUserid the value for sms_channel.sms_channel_userid
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setSmsChannelUserid(String smsChannelUserid) {
        this.smsChannelUserid = smsChannelUserid == null ? null : smsChannelUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.sms_channel_pwd
     *
     * @return the value of sms_channel.sms_channel_pwd
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getSmsChannelPwd() {
        return smsChannelPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.sms_channel_pwd
     *
     * @param smsChannelPwd the value for sms_channel.sms_channel_pwd
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setSmsChannelPwd(String smsChannelPwd) {
        this.smsChannelPwd = smsChannelPwd == null ? null : smsChannelPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.sms_channel_url
     *
     * @return the value of sms_channel.sms_channel_url
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getSmsChannelUrl() {
        return smsChannelUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.sms_channel_url
     *
     * @param smsChannelUrl the value for sms_channel.sms_channel_url
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setSmsChannelUrl(String smsChannelUrl) {
        this.smsChannelUrl = smsChannelUrl == null ? null : smsChannelUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.remark
     *
     * @return the value of sms_channel.remark
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.remark
     *
     * @param remark the value for sms_channel.remark
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.createtor
     *
     * @return the value of sms_channel.createtor
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getCreatetor() {
        return createtor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.createtor
     *
     * @param createtor the value for sms_channel.createtor
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setCreatetor(String createtor) {
        this.createtor = createtor == null ? null : createtor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.created_time
     *
     * @return the value of sms_channel.created_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.created_time
     *
     * @param createdTime the value for sms_channel.created_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.editor
     *
     * @return the value of sms_channel.editor
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.editor
     *
     * @param editor the value for sms_channel.editor
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.updated_time
     *
     * @return the value of sms_channel.updated_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.updated_time
     *
     * @param updatedTime the value for sms_channel.updated_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SmsChannel other = (SmsChannel) that;
        return (this.getSmsChannelId() == null ? other.getSmsChannelId() == null : this.getSmsChannelId().equals(other.getSmsChannelId()))
            && (this.getSmsChannelUserid() == null ? other.getSmsChannelUserid() == null : this.getSmsChannelUserid().equals(other.getSmsChannelUserid()))
            && (this.getSmsChannelPwd() == null ? other.getSmsChannelPwd() == null : this.getSmsChannelPwd().equals(other.getSmsChannelPwd()))
            && (this.getSmsChannelUrl() == null ? other.getSmsChannelUrl() == null : this.getSmsChannelUrl().equals(other.getSmsChannelUrl()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreatetor() == null ? other.getCreatetor() == null : this.getCreatetor().equals(other.getCreatetor()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getEditor() == null ? other.getEditor() == null : this.getEditor().equals(other.getEditor()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSmsChannelId() == null) ? 0 : getSmsChannelId().hashCode());
        result = prime * result + ((getSmsChannelUserid() == null) ? 0 : getSmsChannelUserid().hashCode());
        result = prime * result + ((getSmsChannelPwd() == null) ? 0 : getSmsChannelPwd().hashCode());
        result = prime * result + ((getSmsChannelUrl() == null) ? 0 : getSmsChannelUrl().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreatetor() == null) ? 0 : getCreatetor().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getEditor() == null) ? 0 : getEditor().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }
}