package com.ulic.core.sms.bean;

import java.io.Serializable;
import java.util.Date;

public class SmsRule extends SmsRuleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_rule.sms_template_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String smsTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_rule.sms_channel_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private Long smsChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_rule.remark
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_rule.creator
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_rule.created_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_rule.editor
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_rule.updated_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_rule
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_rule.sms_template_id
     *
     * @return the value of sms_rule.sms_template_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getSmsTemplateId() {
        return smsTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_rule.sms_template_id
     *
     * @param smsTemplateId the value for sms_rule.sms_template_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setSmsTemplateId(String smsTemplateId) {
        this.smsTemplateId = smsTemplateId == null ? null : smsTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_rule.sms_channel_id
     *
     * @return the value of sms_rule.sms_channel_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public Long getSmsChannelId() {
        return smsChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_rule.sms_channel_id
     *
     * @param smsChannelId the value for sms_rule.sms_channel_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setSmsChannelId(Long smsChannelId) {
        this.smsChannelId = smsChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_rule.remark
     *
     * @return the value of sms_rule.remark
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_rule.remark
     *
     * @param remark the value for sms_rule.remark
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_rule.creator
     *
     * @return the value of sms_rule.creator
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_rule.creator
     *
     * @param creator the value for sms_rule.creator
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_rule.created_time
     *
     * @return the value of sms_rule.created_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_rule.created_time
     *
     * @param createdTime the value for sms_rule.created_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_rule.editor
     *
     * @return the value of sms_rule.editor
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_rule.editor
     *
     * @param editor the value for sms_rule.editor
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_rule.updated_time
     *
     * @return the value of sms_rule.updated_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_rule.updated_time
     *
     * @param updatedTime the value for sms_rule.updated_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_rule
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SmsRule other = (SmsRule) that;
        return (this.getBusinessId() == null ? other.getBusinessId() == null : this.getBusinessId().equals(other.getBusinessId()))
            && (this.getSmsType() == null ? other.getSmsType() == null : this.getSmsType().equals(other.getSmsType()))
            && (this.getSmsTemplateId() == null ? other.getSmsTemplateId() == null : this.getSmsTemplateId().equals(other.getSmsTemplateId()))
            && (this.getSmsChannelId() == null ? other.getSmsChannelId() == null : this.getSmsChannelId().equals(other.getSmsChannelId()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getEditor() == null ? other.getEditor() == null : this.getEditor().equals(other.getEditor()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_rule
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBusinessId() == null) ? 0 : getBusinessId().hashCode());
        result = prime * result + ((getSmsType() == null) ? 0 : getSmsType().hashCode());
        result = prime * result + ((getSmsTemplateId() == null) ? 0 : getSmsTemplateId().hashCode());
        result = prime * result + ((getSmsChannelId() == null) ? 0 : getSmsChannelId().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getEditor() == null) ? 0 : getEditor().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }
}