package com.ulic.core.sms.bean;

import java.io.Serializable;

public class SmsRuleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_rule.business_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_rule.sms_type
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String smsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_rule
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_rule.business_id
     *
     * @return the value of sms_rule.business_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_rule.business_id
     *
     * @param businessId the value for sms_rule.business_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_rule.sms_type
     *
     * @return the value of sms_rule.sms_type
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getSmsType() {
        return smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_rule.sms_type
     *
     * @param smsType the value for sms_rule.sms_type
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setSmsType(String smsType) {
        this.smsType = smsType == null ? null : smsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_rule
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SmsRuleKey other = (SmsRuleKey) that;
        return (this.getBusinessId() == null ? other.getBusinessId() == null : this.getBusinessId().equals(other.getBusinessId()))
            && (this.getSmsType() == null ? other.getSmsType() == null : this.getSmsType().equals(other.getSmsType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_rule
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBusinessId() == null) ? 0 : getBusinessId().hashCode());
        result = prime * result + ((getSmsType() == null) ? 0 : getSmsType().hashCode());
        return result;
    }
}