package com.ulic.core.sms.bean;

import java.io.Serializable;
import java.util.Date;

public class SmsTemplate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.sms_template_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String smsTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.sms_type
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String smsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.sms_template_content
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String smsTemplateContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.remark
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.creator
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.created_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.editor
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.updated_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_template
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.sms_template_id
     *
     * @return the value of sms_template.sms_template_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getSmsTemplateId() {
        return smsTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.sms_template_id
     *
     * @param smsTemplateId the value for sms_template.sms_template_id
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setSmsTemplateId(String smsTemplateId) {
        this.smsTemplateId = smsTemplateId == null ? null : smsTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.sms_type
     *
     * @return the value of sms_template.sms_type
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getSmsType() {
        return smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.sms_type
     *
     * @param smsType the value for sms_template.sms_type
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setSmsType(String smsType) {
        this.smsType = smsType == null ? null : smsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.sms_template_content
     *
     * @return the value of sms_template.sms_template_content
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getSmsTemplateContent() {
        return smsTemplateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.sms_template_content
     *
     * @param smsTemplateContent the value for sms_template.sms_template_content
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setSmsTemplateContent(String smsTemplateContent) {
        this.smsTemplateContent = smsTemplateContent == null ? null : smsTemplateContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.remark
     *
     * @return the value of sms_template.remark
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.remark
     *
     * @param remark the value for sms_template.remark
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.creator
     *
     * @return the value of sms_template.creator
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.creator
     *
     * @param creator the value for sms_template.creator
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.created_time
     *
     * @return the value of sms_template.created_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.created_time
     *
     * @param createdTime the value for sms_template.created_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.editor
     *
     * @return the value of sms_template.editor
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.editor
     *
     * @param editor the value for sms_template.editor
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.updated_time
     *
     * @return the value of sms_template.updated_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.updated_time
     *
     * @param updatedTime the value for sms_template.updated_time
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SmsTemplate other = (SmsTemplate) that;
        return (this.getSmsTemplateId() == null ? other.getSmsTemplateId() == null : this.getSmsTemplateId().equals(other.getSmsTemplateId()))
            && (this.getSmsType() == null ? other.getSmsType() == null : this.getSmsType().equals(other.getSmsType()))
            && (this.getSmsTemplateContent() == null ? other.getSmsTemplateContent() == null : this.getSmsTemplateContent().equals(other.getSmsTemplateContent()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getEditor() == null ? other.getEditor() == null : this.getEditor().equals(other.getEditor()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSmsTemplateId() == null) ? 0 : getSmsTemplateId().hashCode());
        result = prime * result + ((getSmsType() == null) ? 0 : getSmsType().hashCode());
        result = prime * result + ((getSmsTemplateContent() == null) ? 0 : getSmsTemplateContent().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getEditor() == null) ? 0 : getEditor().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }
}