package com.ulic.core.sms.dao;

import com.ulic.core.sms.bean.SmsChannel;

public interface SmsChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Long smsChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int insert(SmsChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int insertSelective(SmsChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    SmsChannel selectByPrimaryKey(Long smsChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(SmsChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int updateByPrimaryKey(SmsChannel record);
}