package com.ulic.core.sms.dao;

import com.ulic.core.sms.bean.SmsRule;
import com.ulic.core.sms.bean.SmsRuleKey;

public interface SmsRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_rule
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int deleteByPrimaryKey(SmsRuleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_rule
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int insert(SmsRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_rule
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int insertSelective(SmsRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_rule
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    SmsRule selectByPrimaryKey(SmsRuleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_rule
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(SmsRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_rule
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int updateByPrimaryKey(SmsRule record);
}