package com.ulic.core.sms.dao;

import com.ulic.core.sms.bean.SmsTemplate;

public interface SmsTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int deleteByPrimaryKey(String smsTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int insert(SmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int insertSelective(SmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    SmsTemplate selectByPrimaryKey(String smsTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(SmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated Wed Aug 10 10:43:30 GMT+08:00 2016
     */
    int updateByPrimaryKey(SmsTemplate record);
}